#############DISABLE HYDRA OUTPUTS################

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

#############DISABLE HYDRA OUTPUTS################
input_folder: filter_image_inputs
output_folder: filter_image_outputs

product_names: ["hand bag", "shoe","car","watch or watch dial"]